# Information regarding ideal water quality

#### **About good / bad Notebook**

There are 6 new columns (DRP, EC, Alkalinity, how_good, ideal & unideal).

```DRP``` = 1 if value of ```dissolved reactive phosphorus``` is in the ideal range, else 0,  
```EC``` = 1 if value of ```electrical conductance``` is in the ideal range, else 0,  
```Alkalinity``` = 1 if value of ```total alkalinity``` is in the ideal range, else 0,  
```how_good``` = adding up the three previous columns. Possible values are 1, 2 or 3 (if all of the previous values are 1, then 3).  

```ideal``` = 1 if how_good is 3, else 0,  
```unideal``` = 1 if how_good is 0.  

If Alkalinity, EC and DRP are all outside the ideal water quality range, then there is a 1 in the bad column, otherwise there is a 0.

#### Load Dependencies and Load Data

In [1]:
import pandas as pd
import numpy as np

# read water quality data
df = pd.read_csv('data/wq.csv')
df.describe().round().astype(int)

,latitude,longitude,nir,green,swir16,swir22,ndmi,mndwi,pet,total alkalinity,electrical conductance,dissolved reactive phosphorus,sample_year,pop_density_nn,distance_km_to_pd_cell,river_mouth,river_junction,river_mouthORjunction
count,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093,9093
mean,-28,27,14076,9954,13603,11415,0,0,175,119,488,44,2013,102,0,0,0,0
std,3,3,2781,2636,3155,2403,0,0,29,75,344,51,1,455,0,0,0,0
min,-34,18,3992,4045,3672,3634,0,0,53,5,15,5,2011,0,0,0,0,0
25%,-30,26,12989,9432,12100,10050,0,0,156,55,207,10,2012,2,0,0,0,0
50%,-28,27,14183,9801,13704,11265,0,0,172,113,406,20,2013,10,0,0,0,0
75%,-27,29,15306,10202,15196,12650,0,0,193,171,696,50,2014,54,0,0,0,0
max,-22,32,65535,65535,65535,31202,1,1,271,362,1506,195,2015,6180,1,1,1,1

#### When the primary dataset was acquired, information was provided about the 3 key water quality parameters, and their ideal range of values.

Total Alkalinity - Ideal Range: 20 to 200 mg/L  -> milligrams per liter or ppm  
Electrical Conductance - Ideal Range: < 800 µS/cm -> microsiemens per centimeter  
Dissolved Reactive Phosphorus - Ideal Range: < 100 µg/L -> micrograms per liter

In [2]:
# Add a column for each key value, and label it 1 if the instances value is within the ideal range, and 0 otherwise.
df['DRP'] = [1 if _ < 100 else 0 for _ in df['dissolved reactive phosphorus']]
df['EC'] = [1 if _ < 800 else 0 for _ in df['electrical conductance']]
df['Alkalinity'] = [1 if _ > 20 and _ < 200 else 0 for _ in df['total alkalinity']]

# check for nulls
df.isnull().sum()

country                          0
latitude                         0
longitude                        0
sample date                      0
nir                              0
green                            0
swir16                           0
swir22                           0
ndmi                             0
mndwi                            0
pet                              0
total alkalinity                 0
electrical conductance           0
dissolved reactive phosphorus    0
month                            0
province                         0
sample_year                      0
pop_density_nn                   0
distance_km_to_pd_cell           0
river_mouth                      0
river_junction                   0
river_mouthORjunction            0
DRP                              0
EC                               0
Alkalinity                       0
dtype: int64

In [3]:
# Here are DataFrames with only ideal or undeal water quality
ideal = df[(df['DRP']==1) & (df['EC']==1) & (df['Alkalinity']==1)]
unideal = df[(df['DRP']==0) & (df['EC']==0) & (df['Alkalinity']==0)]

# Add ideal/unideal columns
df = df.assign(how_good=df['Alkalinity']+df['DRP']+df['EC'])
df['ideal'] = np.where(df['how_good'] > 2, 1, 0)
df['unideal'] = np.where(df['how_good'] < 1, 1, 0)
df.head()

,country,latitude,longitude,sample date,nir,green,swir16,swir22,ndmi,mndwi,...,distance_km_to_pd_cell,river_mouth,river_junction,river_mouthORjunction,DRP,EC,Alkalinity,how_good,ideal,unideal
0,South Africa,-26.861111,28.884722,2011-01-03,17658.5,9550.0,13746.5,10574.0,0.124566,-0.180134,...,0.251555,0,0,0,0,1,1,2,0,0
1,South Africa,-26.450000,28.085833,2011-01-03,15210.0,10720.0,17974.0,14201.0,-0.083293,-0.252805,...,0.419537,0,0,0,1,1,1,3,1,0
2,South Africa,-27.671111,27.236944,2011-01-03,14887.0,10943.0,13522.0,11403.0,0.048048,-0.105416,...,0.069958,0,0,0,0,1,1,2,0,0
3,South Africa,-27.356667,27.286389,2011-01-03,16828.5,9502.5,12665.5,9643.0,0.141147,-0.142683,...,0.232396,0,0,0,0,1,1,2,0,0
4,South Africa,-27.010111,26.698083,2011-01-04,12433.5,10433.5,9579.5,8531.5,0.129651,0.042672,...,0.466183,0,0,0,0,1,1,2,0,0

In [4]:
# df.to_pickle('data/good_vs_bad.pkl')

In [5]:
df[df['unideal']==1]

,country,latitude,longitude,sample date,nir,green,swir16,swir22,ndmi,mndwi,...,distance_km_to_pd_cell,river_mouth,river_junction,river_mouthORjunction,DRP,EC,Alkalinity,how_good,ideal,unideal
642,South Africa,-24.034167,31.123611,2011-06-15,14183.0,9801.0,13704.25,11265.25,0.021549,-0.167901,...,0.583894,0,0,0,0,0,0,0,0,1
747,South Africa,-28.376944,24.303056,2011-07-07,13126.5,10384.0,14884.50,12547.50,-0.062761,-0.178107,...,0.294089,0,0,0,0,0,0,0,0,1
1042,South Africa,-27.398611,26.614722,2011-09-06,13482.5,9993.0,14245.50,12485.50,-0.027517,-0.175444,...,0.431484,0,0,0,0,0,0,0,0,1
1298,South Africa,-26.880278,26.965000,2011-11-01,14183.0,9801.0,13704.25,11265.25,0.021549,-0.167901,...,0.379261,0,0,0,0,0,0,0,0,1
1319,South Africa,-29.658056,25.973333,2011-11-05,13931.0,10447.0,14510.50,12488.00,-0.020375,-0.162817,...,0.529429,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,South Africa,-24.034167,31.123611,2015-11-18,14183.0,9801.0,13704.25,11265.25,0.021549,-0.167901,...,0.583894,0,0,0,0,0,0,0,0,1
8962,South Africa,-26.880278,26.965000,2015-11-24,20917.0,16542.0,23017.00,20463.00,-0.047799,-0.163680,...,0.379261,0,0,0,0,0,0,0,0,1
9022,South Africa,-26.880278,26.965000,2015-12-08,14864.0,10677.0,18294.00,15502.00,-0.103444,-0.262918,...,0.379261,0,0,0,0,0,0,0,0,1
9043,South Africa,-27.398611,26.614722,2015-12-10,15670.5,10043.0,14419.00,11729.50,0.041593,-0.178890,...,0.431484,0,0,0,0,0,0,0,0,1
9083,South Africa,-26.880278,26.965000,2015-12-22,14251.0,10629.0,18349.00,15750.00,-0.125706,-0.266409,...,0.379261,0,0,0,0,0,0,0,0,1